### ISSUE TITLE
How to run it without using Docker?

### ISSUE THREAD

**Issue by abdulmanan7** [qiangxue/go-rest-api#1]
Much appreciated your hard work.
Can you please add some description to the readMe file on How to run the API without using Docker.

**Comment by abdulmanan7** [comment]
thanks qiangxue great work and it helps a lot, also if you have time, please add MySQL support.
Mysql is widely used for web development

**Comment by qiangxue** [comment]
Thanks for using this project. Mysql support is as easy as changing the connection string.
