### ISSUE TITLE
how to add pictures related to albums

### ISSUE THREAD

**Issue by kamhlos** [qiangxue/go-rest-api#12]
First off, this is amazing groundwork you have put together. Thanks!

My question is this:
How would you (i.e. what is the recommended way to) implement relational data to an entity?
E.g how would you add pictures as an entity related to an album?

**Comment by kolkov** [comment]
I think that you may use two ways:
* store album pictures as static data, and store picture url in album table.
* store pictures as blobs.

**Comment by kamhlos** [comment]
My question was for relational data in general so pictures was only an example, a better example of what I'm asking would be categories with products. I think both of the approaches you suggested don't play well with other than static data.

**Comment by kamhlos** [comment]
So this is how I'm fetching products related to a category:

**add a new route and function for products related to a category in internal/category/api.go:**
`r.Get("/category/<id>/products", res.products)

func (r resource) products(c *routing.Context) error {
	ctx := c.Request.Context()

	count, err := r.service.CountProducts(ctx, c.Param("id"))
	if err != nil {
		return err
	}

	pages := pagination.NewFromRequest(c.Request, count)
	products, err := r.service.GetProducts(ctx, c.Param("id"), pages.Offset(), pages.Limit())
	if err != nil {
		return err
	}

	pages.Items = products
	return c.Write(pages)
}
`
**then add the two functions for count and GetProducts in internal/category/service.go:**
`// CountProducts of the specified category
func (s service) CountProducts(ctx context.Context, catid string) (int, error) {
	return s.repo.CountProducts(ctx, catid)
}

// GetProducts of the specified category.
func (s service) GetProducts(ctx context.Context, catid string, offset, limit int) ([]Product, error) {
	items, err := s.repo.GetProducts(ctx, catid, offset, limit)
	if err != nil {
		return nil, err
	}
	result := []Product{}
	for _, item := range items {
		result = append(result, Product{item})
	}

	return result, nil
}`

**similarly in internal/category/repository.go:**
`// CountProducts of the specified category.
func (r repository) CountProducts(ctx context.Context, catid string) (int, error) {
	var count int
	err := r.db.With(ctx).
		Select("COUNT(*)").
		From("product").
		Where(dbx.NewExp("category_id={:catid}", dbx.Params{"catid": catid})).
		Row(&count)
	return count, err
}

// GetProducts of the specified category with the specified offset and limit.
func (r repository) GetProducts(ctx context.Context, catid string, offset, limit int) ([]entity.Product, error) {
	var products []entity.Product
	err := r.db.With(ctx).
		Select().
		From("product").
		Where(dbx.NewExp("category_id={:catid}", dbx.Params{"catid": catid})).
		OrderBy("updated_at DESC").
		Offset(int64(offset)).
		Limit(int64(limit)).
		All(&products)
	return products, err
}`

Of course there are some more steps involved, if anyone is interested I'd be happy to show them here

**Comment by kolkov** [comment]
I answered you exactly the question that you voiced. If you meant something else, then you had to ask. There are no psychics here.
