### ISSUE TITLE
Services communication

### ISSUE THREAD

**Issue by mehran-prs** [qiangxue/go-rest-api#4]
Hi @qiangxue! I have one problem and one solution for your template, I'd want to know your comments.

**Problem**: one service needs to interact with other services to handle the request in some scenarios, but if service A needs to service B and service B needs to the A, so we will have dependency-cycle in Go.

example: We have two services: Subscription and Payment. now if the user wants to pay and subscribe, he should request to subscribe and then pay, after payment he redirects to the app and app need to do two jobs:  
- set payment status to `verified` (if payment is ok).
- create a new subscription.

these two services need to interact with each other, how do you handle it in your template?

If we have microservices, so this is not a problem, because our subscription microservice interact with other microservices over a network. but in monolith apps, we should have a solution.

**Solution**: we should implement the subscription and the order services as a subpackage of their packages and on initializing them, pass services interface to them.

services directory structure relative to my solution:
```
├── order
│   ├── orderservice
│   │   └── service.go // the service implementation.
│   └── service.go // the service interface.
└── subscription
    ├── service.go // the service interface.
    └── subscriptionservice
        └── service.go // the service implementation.
```

How do you think about it?

**Comment by kolkov** [comment]
I think that two solutions exists. First: inject order service into subscription service, second: combine two packages into one package.

**Comment by mehran-prs** [comment]
@kolkov about injection I'm with you (just in a monolithic app) and I think we should prevent cycle dependency by defining the implementation of our services in sub-packages.

but about the combination, I think combination just adds complexity and make a messy project.

**Comment by DexterHD** [comment]
@mehran-prs Hi there, according to VaughnVernon (Implementing DDD), if you have 2 services in different Bounded Context, like in your case, they should be integrated using `Domain Events` and `Pub/Sub` pattern.

**Comment by mehran-prs** [comment]
@DexterHD Hi, thanks for your comment.
 yes, we can use pub/sub and events. In microservices Saga is also available.
Assume we have two Domains: `project` and `campaign`.
- In Microservice application: these two domains will have two microservice, so on delete project,
we run a saga to delete all the project's campaigns in the *campaign* microservice, and after that, delete the project. (our saga using events)
- But in monolith application that have these two services just like microservices,  for communication, maybe we have to find a better way to communicate to reduce complexity, something like a direct call


How do you think @DexterHD ?

**Comment by kolkov** [comment]
I think we need to create complex example project based on this boilerplate and test all solutions.

**Comment by mehran-prs** [comment]
@kolkov solutions for the architecture is clear, we just need to implement them in a Go example, [something like this](https://github.com/kgrzybek/modular-monolith-with-ddd#1-Introduction).
maybe its good to have two examples with these architectures:
- Clean architecture(I prefer Hexagonal architecture) + DDD for Monolith application
- Clean architecture(I prefer Hexagonal architecture) + DDD for Microservice (I think we can have two microservice that communicate with each other using both gRPC and saga)

but it can get time (:
